### ISSUE TITLE
Feedback: error on launch

### ISSUE THREAD

**Issue by niclaz** [gzuuus/nostr_startr#9]
Ran a fresh install on a linux box - made nostr_console executable and launched nostr_startr

When selecting option 1 to start nostr_console it fails and reverts to the main menu of the python program without throwing an error. 

I tried to get a logfile by debugging by using the following command: `$ python3 startr_app.py echo " " >> log.file`

Interesting the python program did not throw an error at all but instead I got this output on my terminal:

```
Unhandled exception:
HandshakeException: Handshake error in client (OS Error: 
	SSLV3_ALERT_HANDSHAKE_FAILURE(tls_record.cc:594)
	HANDSHAKE_FAILURE_ON_CLIENT_HELLO(handshake.cc:644))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040)
<asynchronous suspension>

```
Submitting for your input and review - no specific request or feedback

**Comment by gzuuus** [comment]
Yes, it is a known bug in @vishalxl 's nostr_console, you can follow it in this issue. 
[github.com/vishalxl/nostr_console/issues/78](https://github.com/vishalxl/nostr_console/issues/78)
At the moment nostr_console is not usable even if you select your own relays. Hopefully the dev will fix this.
The python log does not output the error because the bug happens outside of startr in nostr_console and no stdout capture is done at this time.
